"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones, configureBoneyard } from 'boneyard-js/react'

import _home_stats from './home-stats.bones.json'
import _home_cases_list from './home-cases-list.bones.json'
import _home_clients_list from './home-clients-list.bones.json'
import _home_agenda from './home-agenda.bones.json'
import _cases_stats from './cases-stats.bones.json'
import _cases_table from './cases-table.bones.json'
import _clients_stats from './clients-stats.bones.json'
import _clients_table from './clients-table.bones.json'

configureBoneyard({"color":"#e8e8e8","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#f0f0f0","darkShimmerColor":"#333333","speed":"1.8s","shimmerAngle":110})

registerBones({
  "home-stats": _home_stats,
  "home-cases-list": _home_cases_list,
  "home-clients-list": _home_clients_list,
  "home-agenda": _home_agenda,
  "cases-stats": _cases_stats,
  "cases-table": _cases_table,
  "clients-stats": _clients_stats,
  "clients-table": _clients_table,
})
